# Generated by Django 3.1.12 on 2021-12-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211227_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='age',
            field=models.IntegerField(),
        ),
    ]
