# Generated by Django 3.1.12 on 2021-12-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211227_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
