# Generated by Django 3.0.5 on 2022-02-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_crud_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='image',
        ),
    ]
