# Generated by Django 3.0.5 on 2022-02-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_crud_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phonenumber', models.IntegerField()),
                ('username', models.IntegerField()),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
